apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: youtube-backend-clone
build:
  artifacts:
  - image: yusuferen/youtube-backend
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - infra/k8s/ingress.yaml
    - infra/k8s/deployment.yaml
